channels:
  - conda-forge
name: eradiate-training-20251016
dependencies:
  - python=3.12
  - pip
  - pip:
    - eradiate[kernel]==1.0.*
    - sf_hamilton<1.89
    - ipykernel
    - ipywidgets
    - jupyterlab
    - netcdf4
    - seaborn
